name: Build

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        java: [ 8, 9, 10, 11, 12, 13 ]
    name: Java ${{ matrix.java }} build
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - uses: actions/upload-artifact@v2
        with:
          name: delight-rhino-sandbox
          path: target/delight-rhino-sandbox-*.jar
